services:
  web:
    build: .
    entrypoint: ["bun", "dev"]
    ports:
      - "3000:3000"
    env_file:
      - path: .env
        required: true
    environment:
      POSTGRES_HOST: "db"
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app
        - action: rebuild
          path: package.json
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    shm_size: 128mb
    env_file:
      - path: .env
        required: true
